// Generated by CoffeeScript 1.3.3
var ProductDetailController, ProductListController;

ProductListController = function($scope, $http) {
  $scope.title = "Joly Sushi";
  $http.get('data/data.json').success(function(data) {
    $scope.sushis = data;
    return $scope.totalPrice = function() {
      return $scope.sushis.reduce((function(a, b) {
        return a + b.price;
      }), 0);
    };
  });
  $scope.orderProp = 'price';
};

ProductDetailController = function($scope, $routeParams) {
  return $scope.sushiId = $routeParams["sushiId"];
};

/* ProductDetailController.$inject = ['$scope',"$routeParams"]
*/

