// Generated by CoffeeScript 1.3.3
var ProductDetailController, ProductListController;

ProductListController = function($scope, $http) {
  $scope.title = "Joly Sushi";
  $http.get('data/data.json').success(function(data) {
    $scope.sushis = data;
    return $scope.totalPrice = function() {
      return $scope.sushis.reduce((function(a, b) {
        return a + b.price;
      }), 0);
    };
  });
  $scope.orderProp = 'price';
};

ProductDetailController = function($scope, $routeParams, $http) {
  $scope.sushiId = $routeParams["sushiId"];
  $http.get('data/data.json').success(function(datas) {
    var data, _i, _len;
    for (_i = 0, _len = datas.length; _i < _len; _i++) {
      data = datas[_i];
      if (data.id === parseInt($scope.sushiId, 10)) {
        $scope.sushi = data;
        return;
      }
    }
  });
};

/* ProductDetailController.$inject = ['$scope',"$routeParams"]
*/

