// Generated by CoffeeScript 1.3.3
/*
    créer un filter personalisé
*/

angular.module("sushiFilters", []).filter('totalprice', function() {
  return function(sushis) {
    if (sushis == null) {
      sushis = [
        {
          price: 0
        }
      ];
    }
    return sushis.reduce((function(a, b) {
      return a + b.price;
    }), 0);
  };
});
